# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
